/* =====================================================================
   PayLink config — FILL THESE IN with your Supabase project values.
   1. Create a free project at https://supabase.com
   2. Run supabase/schema.sql in the SQL editor
   3. Project Settings -> API -> copy the URL and anon/public key below
   These are PUBLIC (browser-safe) values — safe to ship in a static site.
   ===================================================================== */
window.PAYLINK_CONFIG = {
  SUPABASE_URL: 'https://titfqwvebinneeobyobp.supabase.co',
  SUPABASE_ANON_KEY: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRpdGZxd3ZlYmlubmVlb2J5b2JwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODY4OTA1ODQsImV4cCI6MjEwMjQ2NjU4NH0.eWiTpsvzhDtM73IJOqYql4q-rwkUl7qF77p2WdezX8A',

  // ----- Admin only (treat as secrets) -----
  // Single password to open the admin dashboard, like an env key.
  ADMIN_PASSWORD: 'YUNGMONI',
  // Service-role key (bypasses RLS). It is visible in the browser source, so keep
  // the admin page URL private and use a strong ADMIN_PASSWORD. For higher
  // security later, move admin writes behind a serverless function instead.
  SUPABASE_SERVICE_ROLE_KEY: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRpdGZxd3ZlYmlubmVlb2J5b2JwIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc4Njg5MDU4NCwiZXhwIjoyMTAyNDY2NTg0fQ.B3_QDn3u766vD2GtpxgbWunJpt0iUcxc7i2PGHVbQXI',
};

/* Currency metadata used across admin + client pages.
   `country` is only used to make the admin search box match by country name.
   Display uses `symbol` (renders everywhere) instead of flag emoji.
   CAD is the business's target currency and is filtered out of pickers. */
window.CURRENCIES = {
  AED: { symbol: 'د.إ', name: 'UAE Dirham', country: 'United Arab Emirates' },
  AFN: { symbol: '؋', name: 'Afghan Afghani', country: 'Afghanistan' },
  ALL: { symbol: 'L', name: 'Albanian Lek', country: 'Albania' },
  AMD: { symbol: '֏', name: 'Armenian Dram', country: 'Armenia' },
  ANG: { symbol: 'ƒ', name: 'Netherlands Antillean Guilder', country: 'Curaçao' },
  AOA: { symbol: 'Kz', name: 'Angolan Kwanza', country: 'Angola' },
  ARS: { symbol: '$', name: 'Argentine Peso', country: 'Argentina' },
  AUD: { symbol: 'A$', name: 'Australian Dollar', country: 'Australia' },
  AWG: { symbol: 'ƒ', name: 'Aruban Florin', country: 'Aruba' },
  AZN: { symbol: '₼', name: 'Azerbaijani Manat', country: 'Azerbaijan' },
  BAM: { symbol: 'KM', name: 'Bosnia-Herzegovina Convertible Mark', country: 'Bosnia' },
  BBD: { symbol: '$', name: 'Barbadian Dollar', country: 'Barbados' },
  BDT: { symbol: '৳', name: 'Bangladeshi Taka', country: 'Bangladesh' },
  BGN: { symbol: 'лв', name: 'Bulgarian Lev', country: 'Bulgaria' },
  BHD: { symbol: '.د.ب', name: 'Bahraini Dinar', country: 'Bahrain' },
  BIF: { symbol: 'Fr', name: 'Burundian Franc', country: 'Burundi' },
  BMD: { symbol: '$', name: 'Bermudan Dollar', country: 'Bermuda' },
  BND: { symbol: '$', name: 'Brunei Dollar', country: 'Brunei' },
  BOB: { symbol: 'Bs.', name: 'Bolivian Boliviano', country: 'Bolivia' },
  BRL: { symbol: 'R$', name: 'Brazilian Real', country: 'Brazil' },
  BSD: { symbol: '$', name: 'Bahamian Dollar', country: 'Bahamas' },
  BTN: { symbol: 'Nu.', name: 'Bhutanese Ngultrum', country: 'Bhutan' },
  BWP: { symbol: 'P', name: 'Botswanan Pula', country: 'Botswana' },
  BYN: { symbol: 'Br', name: 'Belarusian Ruble', country: 'Belarus' },
  BZD: { symbol: '$', name: 'Belize Dollar', country: 'Belize' },
  CAD: { symbol: 'C$', name: 'Canadian Dollar', country: 'Canada' },
  CDF: { symbol: 'FC', name: 'Congolese Franc', country: 'DR Congo' },
  CHF: { symbol: 'Fr', name: 'Swiss Franc', country: 'Switzerland' },
  CLP: { symbol: '$', name: 'Chilean Peso', country: 'Chile' },
  CNY: { symbol: '¥', name: 'Chinese Yuan', country: 'China' },
  COP: { symbol: '$', name: 'Colombian Peso', country: 'Colombia' },
  CRC: { symbol: '₡', name: 'Costa Rican Colón', country: 'Costa Rica' },
  CUP: { symbol: '$', name: 'Cuban Peso', country: 'Cuba' },
  CVE: { symbol: '$', name: 'Cape Verdean Escudo', country: 'Cabo Verde' },
  CZK: { symbol: 'Kč', name: 'Czech Koruna', country: 'Czechia' },
  DJF: { symbol: 'Fdj', name: 'Djiboutian Franc', country: 'Djibouti' },
  DKK: { symbol: 'kr', name: 'Danish Krone', country: 'Denmark' },
  DOP: { symbol: '$', name: 'Dominican Peso', country: 'Dominican Republic' },
  DZD: { symbol: 'د.ج', name: 'Algerian Dinar', country: 'Algeria' },
  EGP: { symbol: '£', name: 'Egyptian Pound', country: 'Egypt' },
  ERN: { symbol: 'Nfk', name: 'Eritrean Nakfa', country: 'Eritrea' },
  ETB: { symbol: 'Br', name: 'Ethiopian Birr', country: 'Ethiopia' },
  EUR: { symbol: '€', name: 'Euro', country: 'Eurozone, Germany, France, Spain, Italy' },
  FJD: { symbol: '$', name: 'Fijian Dollar', country: 'Fiji' },
  FKP: { symbol: '£', name: 'Falkland Islands Pound', country: 'Falkland Islands' },
  GEL: { symbol: '₾', name: 'Georgian Lari', country: 'Georgia' },
  GHS: { symbol: '₵', name: 'Ghanaian Cedi', country: 'Ghana' },
  GIP: { symbol: '£', name: 'Gibraltar Pound', country: 'Gibraltar' },
  GMD: { symbol: 'D', name: 'Gambian Dalasi', country: 'Gambia' },
  GNF: { symbol: 'FG', name: 'Guinean Franc', country: 'Guinea' },
  GTQ: { symbol: 'Q', name: 'Guatemalan Quetzal', country: 'Guatemala' },
  GYD: { symbol: '$', name: 'Guyanese Dollar', country: 'Guyana' },
  HKD: { symbol: 'HK$', name: 'Hong Kong Dollar', country: 'Hong Kong' },
  HNL: { symbol: 'L', name: 'Honduran Lempira', country: 'Honduras' },
  HUF: { symbol: 'Ft', name: 'Hungarian Forint', country: 'Hungary' },
  IDR: { symbol: 'Rp', name: 'Indonesian Rupiah', country: 'Indonesia' },
  ILS: { symbol: '₪', name: 'Israeli New Shekel', country: 'Israel' },
  INR: { symbol: '₹', name: 'Indian Rupee', country: 'India' },
  IQD: { symbol: 'ع.د', name: 'Iraqi Dinar', country: 'Iraq' },
  IRR: { symbol: '﷼', name: 'Iranian Rial', country: 'Iran' },
  ISK: { symbol: 'kr', name: 'Icelandic Króna', country: 'Iceland' },
  JMD: { symbol: '$', name: 'Jamaican Dollar', country: 'Jamaica' },
  JOD: { symbol: 'د.ا', name: 'Jordanian Dinar', country: 'Jordan' },
  JPY: { symbol: '¥', name: 'Japanese Yen', country: 'Japan' },
  KES: { symbol: 'KSh', name: 'Kenyan Shilling', country: 'Kenya' },
  KGS: { symbol: 'сом', name: 'Kyrgystani Som', country: 'Kyrgyzstan' },
  KHR: { symbol: '៛', name: 'Cambodian Riel', country: 'Cambodia' },
  KMF: { symbol: 'CF', name: 'Comorian Franc', country: 'Comoros' },
  KRW: { symbol: '₩', name: 'South Korean Won', country: 'South Korea' },
  KWD: { symbol: 'د.ك', name: 'Kuwaiti Dinar', country: 'Kuwait' },
  KYD: { symbol: '$', name: 'Cayman Islands Dollar', country: 'Cayman Islands' },
  KZT: { symbol: '₸', name: 'Kazakhstani Tenge', country: 'Kazakhstan' },
  LAK: { symbol: '₭', name: 'Lao Kip', country: 'Laos' },
  LBP: { symbol: 'ل.ل', name: 'Lebanese Pound', country: 'Lebanon' },
  LKR: { symbol: 'Rs', name: 'Sri Lankan Rupee', country: 'Sri Lanka' },
  LRD: { symbol: '$', name: 'Liberian Dollar', country: 'Liberia' },
  LSL: { symbol: 'L', name: 'Lesotho Loti', country: 'Lesotho' },
  LYD: { symbol: 'ل.د', name: 'Libyan Dinar', country: 'Libya' },
  MAD: { symbol: 'د.م.', name: 'Moroccan Dirham', country: 'Morocco' },
  MDL: { symbol: 'L', name: 'Moldovan Leu', country: 'Moldova' },
  MGA: { symbol: 'Ar', name: 'Malagasy Ariary', country: 'Madagascar' },
  MKD: { symbol: 'ден', name: 'Macedonian Denar', country: 'North Macedonia' },
  MMK: { symbol: 'K', name: 'Burmese Kyat', country: 'Myanmar' },
  MNT: { symbol: '₮', name: 'Mongolian Tugrik', country: 'Mongolia' },
  MOP: { symbol: 'MOP$', name: 'Macanese Pataca', country: 'Macau' },
  MUR: { symbol: '₨', name: 'Mauritian Rupee', country: 'Mauritius' },
  MVR: { symbol: 'MVR', name: 'Maldivian Rufiyaa', country: 'Maldives' },
  MWK: { symbol: 'MK', name: 'Malawian Kwacha', country: 'Malawi' },
  MXN: { symbol: '$', name: 'Mexican Peso', country: 'Mexico' },
  MYR: { symbol: 'RM', name: 'Malaysian Ringgit', country: 'Malaysia' },
  MZN: { symbol: 'MT', name: 'Mozambican Metical', country: 'Mozambique' },
  NAD: { symbol: '$', name: 'Namibian Dollar', country: 'Namibia' },
  NGN: { symbol: '₦', name: 'Nigerian Naira', country: 'Nigeria' },
  NIO: { symbol: 'C$', name: 'Nicaraguan Córdoba', country: 'Nicaragua' },
  NOK: { symbol: 'kr', name: 'Norwegian Krone', country: 'Norway' },
  NPR: { symbol: '₨', name: 'Nepalese Rupee', country: 'Nepal' },
  NZD: { symbol: 'NZ$', name: 'New Zealand Dollar', country: 'New Zealand' },
  OMR: { symbol: '﷼', name: 'Omani Rial', country: 'Oman' },
  PAB: { symbol: 'B/.', name: 'Panamanian Balboa', country: 'Panama' },
  PEN: { symbol: 'S/', name: 'Peruvian Sol', country: 'Peru' },
  PGK: { symbol: 'K', name: 'Papua New Guinean Kina', country: 'Papua New Guinea' },
  PHP: { symbol: '₱', name: 'Philippine Peso', country: 'Philippines' },
  PKR: { symbol: '₨', name: 'Pakistani Rupee', country: 'Pakistan' },
  PLN: { symbol: 'zł', name: 'Polish Złoty', country: 'Poland' },
  PYG: { symbol: '₲', name: 'Paraguayan Guarani', country: 'Paraguay' },
  QAR: { symbol: '﷼', name: 'Qatari Riyal', country: 'Qatar' },
  RON: { symbol: 'lei', name: 'Romanian Leu', country: 'Romania' },
  RSD: { symbol: 'дин', name: 'Serbian Dinar', country: 'Serbia' },
  RUB: { symbol: '₽', name: 'Russian Ruble', country: 'Russia' },
  RWF: { symbol: 'FRw', name: 'Rwandan Franc', country: 'Rwanda' },
  SAR: { symbol: '﷼', name: 'Saudi Riyal', country: 'Saudi Arabia' },
  SBD: { symbol: '$', name: 'Solomon Islands Dollar', country: 'Solomon Islands' },
  SCR: { symbol: '₨', name: 'Seychellois Rupee', country: 'Seychelles' },
  SDG: { symbol: 'ج.س.', name: 'Sudanese Pound', country: 'Sudan' },
  SEK: { symbol: 'kr', name: 'Swedish Krona', country: 'Sweden' },
  SGD: { symbol: 'S$', name: 'Singapore Dollar', country: 'Singapore' },
  SHP: { symbol: '£', name: 'Saint Helena Pound', country: 'Saint Helena' },
  SLE: { symbol: 'Le', name: 'Sierra Leonean Leone', country: 'Sierra Leone' },
  SOS: { symbol: 'Sh', name: 'Somali Shilling', country: 'Somalia' },
  SRD: { symbol: '$', name: 'Surinamese Dollar', country: 'Suriname' },
  SSP: { symbol: '£', name: 'South Sudanese Pound', country: 'South Sudan' },
  STN: { symbol: 'Db', name: 'São Tomé and Príncipe Dobra', country: 'São Tomé' },
  SVC: { symbol: '₡', name: 'Salvadoran Colón', country: 'El Salvador' },
  SYP: { symbol: '£', name: 'Syrian Pound', country: 'Syria' },
  SZL: { symbol: 'E', name: 'Eswatini Lilangeni', country: 'Eswatini' },
  THB: { symbol: '฿', name: 'Thai Baht', country: 'Thailand' },
  TJS: { symbol: 'SM', name: 'Tajikistani Somoni', country: 'Tajikistan' },
  TMT: { symbol: 'T', name: 'Turkmenistani Manat', country: 'Turkmenistan' },
  TND: { symbol: 'د.ت', name: 'Tunisian Dinar', country: 'Tunisia' },
  TOP: { symbol: 'T$', name: 'Tongan Paʻanga', country: 'Tonga' },
  TRY: { symbol: '₺', name: 'Turkish Lira', country: 'Turkey' },
  TTD: { symbol: '$', name: 'Trinidad and Tobago Dollar', country: 'Trinidad' },
  TWD: { symbol: 'NT$', name: 'New Taiwan Dollar', country: 'Taiwan' },
  TZS: { symbol: 'TSh', name: 'Tanzanian Shilling', country: 'Tanzania' },
  UAH: { symbol: '₴', name: 'Ukrainian Hryvnia', country: 'Ukraine' },
  UGX: { symbol: 'USh', name: 'Ugandan Shilling', country: 'Uganda' },
  USD: { symbol: '$', name: 'US Dollar', country: 'United States' },
  UYU: { symbol: '$U', name: 'Uruguayan Peso', country: 'Uruguay' },
  UZS: { symbol: 'soʻm', name: 'Uzbekistani Som', country: 'Uzbekistan' },
  VES: { symbol: 'Bs', name: 'Venezuelan Bolívar', country: 'Venezuela' },
  VND: { symbol: '₫', name: 'Vietnamese Dong', country: 'Vietnam' },
  VUV: { symbol: 'VT', name: 'Vanuatu Vatu', country: 'Vanuatu' },
  WST: { symbol: 'WS$', name: 'Samoan Tālā', country: 'Samoa' },
  XAF: { symbol: 'FCFA', name: 'Central African CFA Franc', country: 'Central Africa' },
  XCD: { symbol: '$', name: 'East Caribbean Dollar', country: 'East Caribbean' },
  XOF: { symbol: 'CFA', name: 'West African CFA Franc', country: 'West Africa' },
  XPF: { symbol: '₣', name: 'CFP Franc', country: 'French Polynesia' },
  YER: { symbol: '﷼', name: 'Yemeni Rial', country: 'Yemen' },
  ZAR: { symbol: 'R', name: 'South African Rand', country: 'South Africa' },
  ZMW: { symbol: 'ZK', name: 'Zambian Kwacha', country: 'Zambia' },
  ZWL: { symbol: '$', name: 'Zimbabwean Dollar', country: 'Zimbabwe' },
};
/* The business always receives CAD (per spec) */
window.TARGET_CURRENCY = 'CAD';

/* True only once real Supabase values are pasted in below */
window.isPaylinkConfigured = function () {
  const c = window.PAYLINK_CONFIG || {};
  return Boolean(
    c.SUPABASE_URL && c.SUPABASE_ANON_KEY &&
    c.ADMIN_PASSWORD && c.ADMIN_PASSWORD !== 'CHANGE_THIS_ADMIN_PASSWORD' &&
    c.SUPABASE_SERVICE_ROLE_KEY && c.SUPABASE_SERVICE_ROLE_KEY !== 'YOUR-SERVICE-ROLE-KEY' &&
    !c.SUPABASE_URL.includes('YOUR-PROJECT') &&
    !c.SUPABASE_ANON_KEY.includes('YOUR-ANON')
  );
};
